openapi: 3.0.3
info:
  title: School Management
  description: School Management API as a sample app
  version: 1.0.0
servers:
  - url: "http://localhost:8080/"
    description: local
components:
  schemas:
    Student:
        required:
            - id
            - name
        type: object
        properties:
          id:
            type: integer
            format: int64
            example: 10
          name:
            type: string
            example: Bennet
    School:
      required:
        - id
        - name
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          example: Theodor-Litt-Schule
paths:
  /students/{id}:
    get:
      operationId: getStudentById
      summary: Get Student by Id
      description: Provides a student.
      parameters:
        - name: id
          in: path
          description: Student id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Student received.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'

  /students:
    get:
      operationId: getStudents
      summary: Gets all students
      responses:
        '200':
          description: Get List of Students
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Student'
